#*ğŸ¤–Este Pipeline de CI se activa al PUSHEAR o MERGEAR en ramas de tareas que no sean QA ni Main, y consiste en ejecutar los tests de una US e importar los resultados a Jira!ğŸš€

name: ğŸ§ªPlaywright Sanity Testing
run-name: ${{github.actor}}ğŸ‘¨ğŸ»â€ğŸ”¬ ran TestSuite in ${{github.ref_name}}
on:
  push:
    branches: ['test/GX3-1901/elements_upload_and_download'] #! Cambia "TuBranchAqui" por el nombre de tu rama de tarea.

jobs:
  TestSuite:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“˜ Checkout Repo
      uses: actions/checkout@v3

    - name: ğŸ’¿ Installing Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: ğŸ’¿Yarn Setup
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 18

    - name: ğŸ§¬ Install Project Dependencies
      run: |
        yarn

    - name: ğŸ­ï¸ Installing Playwright And Browsers
      run: |
        yarn pw:install

    - name: âœ… ğŸ§ªTest Suite Execution
      run: | #todo: EDITAR AQUÃ EL ARCHIVO SUITE A EJECUTAR:
        yarn test:ci tests/specs/elements/uploadDownload_GX3-1901.test.ts

    - name: ğŸ“ŠGenerate Allure Report
      run: |
        yarn allure:open

    - name: ğŸ“¡Upload Artifact - Allure Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: allure-report
        retention-days: 15

    - name: âœ…Import Test Results to Xray
      if: always()
      uses: mikepenz/xray-action@v2
      with:
        username: ${{secrets.XRAY_CLIENT_ID}}
        password: ${{secrets.XRAY_CLIENT_SECRET}}
        testFormat: 'junit'
        testPaths: 'test-junit-report/main-importer-report.xml'
        testExecKey: 'GX3-1908' #!Cambiar a tu TX correspondiente.
        projectKey: 'GX3' #!Cambiar a tu Proyecto Level correspondiente.

    - name: ğŸ””Slack Notification of Done
      if: always()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ariâœ¨
        SLACK_MESSAGE: ':test_tube: BLACKHOLE Playwright Project -- Test Execution is Done and updated in Jira :rocket:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp
